using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using SlotGame.Data;

namespace SlotGame.Core
{
    /// <summary>
    /// Controls individual reel behavior: spinning, infinite wrapping, and 
    /// snapping to RNG results with pixel-perfect alignment.
    /// </summary>
    public class ReelController : MonoBehaviour
    {
        [Header("References")]
        [Tooltip("The RectTransform that acts as the parent for spawned symbols.")]
        [SerializeField] private RectTransform symbolsContainer;
        [Tooltip("The Symbol Prefab asset (should be 96x96 with Pivot 0.5, 0.5).")]
        [SerializeField] private GameObject symbolPrefab;
        [Tooltip("The list of available symbols for randomizing during the spin blur.")]
        [SerializeField] private List<SymbolData> availableSymbols;

        [Header("Spin Settings")]
        [SerializeField] private float spinSpeed = 1500f;
        [SerializeField] private float symbolHeight = 96f;
        [SerializeField] private float spacing = 10f;

        // Optimized caching for runtime performance
        private readonly List<RectTransform> _symbolRects = new List<RectTransform>();
        private readonly List<Image> _symbolImages = new List<Image>();

        private bool _isSpinning;
        private float _thresholdY;
        private float _totalStep;
        private SymbolData _targetResult;

        private void Start()
        {
            _totalStep = symbolHeight + spacing;
            SetupInitialReelState();
        }

        /// <summary>
        /// Populates the reel with symbols and centers the stack on Y=0.
        /// </summary>
        private void SetupInitialReelState()
        {
            // Threshold is set to 2 symbols down to keep top/bottom symbols visible during wrap
            _thresholdY = -2 * _totalStep;

            for (int i = 0; i < 6; i++)
            {
                GameObject symbolInstance = Instantiate(symbolPrefab, symbolsContainer);
                RectTransform rt = symbolInstance.GetComponent<RectTransform>();
                Image img = symbolInstance.GetComponent<Image>();

                // (i - 2) ensures the symbols are distributed equally above and below the center (0,0)
                rt.anchoredPosition = new Vector2(0, (i - 2) * _totalStep);

                // Set initial random sprite
                img.sprite = availableSymbols[Random.Range(0, availableSymbols.Count)].SymbolSprite;

                _symbolRects.Add(rt);
                _symbolImages.Add(img);
            }
        }

        public void StartSpin()
        {
            if (_isSpinning) return;
            _isSpinning = true;
            StartCoroutine(SpinUpdate());
        }

        /// <summary>
        /// Commands the reel to stop and provides the result generated by the Manager's RNG.
        /// </summary>
        public void StopSpin(SymbolData result)
        {
            _targetResult = result;
            _isSpinning = false;
        }

        private IEnumerator SpinUpdate()
        {
            while (_isSpinning)
            {
                float moveAmount = spinSpeed * Time.deltaTime;

                for (int i = 0; i < _symbolRects.Count; i++)
                {
                    _symbolRects[i].anchoredPosition -= new Vector2(0, moveAmount);

                    // Wrap Logic: Teleport symbol to top if it passes the bottom threshold
                    if (_symbolRects[i].anchoredPosition.y <= _thresholdY)
                    {
                        float wrapBuffer = _symbolRects.Count * _totalStep;
                        _symbolRects[i].anchoredPosition += new Vector2(0, wrapBuffer);

                        // Randomize sprite while spinning to simulate motion
                        _symbolImages[i].sprite = availableSymbols[Random.Range(0, availableSymbols.Count)].SymbolSprite;
                    }
                }
                yield return null;
            }

            FinalizePosition();
        }

        /// <summary>
        /// Mathematically aligns the reel so the winning symbol sits exactly at Y=0.
        /// </summary>
        private void FinalizePosition()
        {
            if (_symbolRects.Count == 0) return;

            // 1. Identify the symbol closest to the local center (Y=0)
            RectTransform closestSymbol = _symbolRects[0];
            int closestIndex = 0;
            float minDistance = Mathf.Abs(_symbolRects[0].anchoredPosition.y);

            for (int i = 1; i < _symbolRects.Count; i++)
            {
                float dist = Mathf.Abs(_symbolRects[i].anchoredPosition.y);
                if (dist < minDistance)
                {
                    minDistance = dist;
                    closestSymbol = _symbolRects[i];
                    closestIndex = i;
                }
            }

            // 2. Inject the pre-determined RNG result sprite
            if (_targetResult != null)
            {
                _symbolImages[closestIndex].sprite = _targetResult.SymbolSprite;
            }

            // 3. Align the entire stack so the winning symbol is perfectly centered at 0
            float alignmentOffset = -closestSymbol.anchoredPosition.y;
            foreach (var rt in _symbolRects)
            {
                // Rounding to nearest integer ensures pixel art remains crisp on the UI grid
                float newY = Mathf.Round(rt.anchoredPosition.y + alignmentOffset);
                rt.anchoredPosition = new Vector2(0, newY);
            }

            HandlePostSnapWrap();
        }

        /// <summary>
        /// Cleanup pass to ensure no symbols remain outside visibility bounds after snapping.
        /// </summary>
        private void HandlePostSnapWrap()
        {
            float wrapBuffer = _symbolRects.Count * _totalStep;

            foreach (var rt in _symbolRects)
            {
                if (rt.anchoredPosition.y <= _thresholdY)
                {
                    rt.anchoredPosition += new Vector2(0, wrapBuffer);
                }
                else if (rt.anchoredPosition.y > (wrapBuffer + _thresholdY))
                {
                    rt.anchoredPosition -= new Vector2(0, wrapBuffer);
                }
            }
        }
    }
}